name: freeflow
description: freeflow in app

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_svg: ^1.1.5
  overlay_support: ^2.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  permission_handler: ^9.2.0
  cloud_functions: ^4.0.6
  rxdart: ^0.27.7
  flutter_sodium: ^0.2.0
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/